import { expect, test } from '@playwright/test';
import { resetEmulators } from '../helpers/emulator';
import { TestStepHelper } from '../helpers/test-step-helper';
import { startTask, openDetails, saveDetails } from '../helpers/task-details';

test.use({ actionTimeout: 10000 });

test('phone-first date and repeat journey', async ({ page, request }, testInfo) => {
	await resetEmulators(request);
	const helper = new TestStepHelper(
		page,
		testInfo,
		testInfo.project.name.replaceAll(' ', '-'),
		true
	);
	helper.setMetadata(
		'Task details: first repeating task',
		'Choose a first date, configure a schedule, preview it, save, and reopen. Real app screens, generated by the verified story.'
	);
	await startTask(page);
	await helper.step('undated_task', {
		description: 'Repeat is available without finding an unlabeled checkbox.',
		verifications: [
			{
				spec: 'The repeat row is enabled and the unchanged draft cannot be saved',
				check: async () => {
					await expect(page.getByRole('button', { name: /^Repeat / })).toBeEnabled();
					await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled();
				}
			}
		]
	});
	await page.getByRole('button', { name: /^Repeat / }).click();
	await page.locator('input[aria-label="Due date"]').fill('2026-09-18');
	await helper.step('choose_first_date', {
		verifications: [
			{
				spec: 'The calendar highlights the entered first date',
				check: async () =>
					expect(
						page.getByRole('button', { name: 'Fri, Sep 18, 2026', exact: true })
					).toHaveAttribute('aria-pressed', 'true')
			}
		]
	});
	await page.getByRole('button', { name: 'Next month', exact: true }).click();
	await page.getByRole('button', { name: 'Previous month', exact: true }).click();
	await page.getByRole('button', { name: 'Fri, Sep 18, 2026', exact: true }).click();
	await page.getByRole('button', { name: 'Done', exact: true }).click();
	await page.getByRole('radio', { name: /^Weekly/ }).check();
	await page.getByLabel('Every', { exact: true }).fill('2');
	await helper.step('weekly_schedule', {
		verifications: [
			{
				spec: 'All six rules are available and the full schedule is readable',
				check: async () => {
					await expect(page.getByRole('radio')).toHaveCount(6);
					await expect(page.getByText('Every 2 weeks on Friday', { exact: true })).toBeVisible();
				}
			}
		]
	});
	await page.getByRole('button', { name: 'Done', exact: true }).click();
	await helper.step('review_before_save', {
		verifications: [
			{
				spec: 'Upcoming dates include Sep 18, Oct 2 and Oct 16',
				check: async () => {
					const preview = page.getByRole('region', { name: 'Upcoming due dates' });
					await expect(preview).toContainText('Fri, Sep 18, 2026');
					await expect(preview).toContainText('Fri, Oct 2, 2026');
					await expect(preview).toContainText('Fri, Oct 16, 2026');
				}
			}
		]
	});
	await saveDetails(page);
	await expect(
		page.getByRole('button', { name: 'Edit details for Water the plants' })
	).toBeFocused();
	await page.reload();
	await openDetails(page);
	await helper.step('saved_and_reloaded', {
		verifications: [
			{
				spec: 'The date and repeat rule survive a full reload',
				check: async () => {
					await expect(page.getByRole('button', { name: /^Due date/ })).toContainText(
						'Fri, Sep 18, 2026'
					);
					await expect(page.getByRole('button', { name: /^Repeat / })).toContainText(
						'Every 2 weeks on Friday'
					);
				}
			}
		]
	});
	await helper.generateDocs();
});
